// <auto-generated />
using Catalog.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.DataAccess.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20240321170639_seeding_books")]
    partial class seeding_books
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.DataAccess.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("BookTopicId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("BookTopicId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookTopicId = 1,
                            Price = 15.0,
                            Quantity = 5,
                            Title = "How to get a good grade in DOS in 40 minutes a day"
                        },
                        new
                        {
                            BookId = 2,
                            BookTopicId = 1,
                            Price = 20.0,
                            Quantity = 3,
                            Title = "RPCs for Noobs"
                        },
                        new
                        {
                            BookId = 3,
                            BookTopicId = 2,
                            Price = 15.0,
                            Quantity = 5,
                            Title = "Xen and the Art of Surviving Undergraduate School."
                        },
                        new
                        {
                            BookId = 4,
                            BookTopicId = 2,
                            Price = 15.0,
                            Quantity = 5,
                            Title = "Cooking for the Impatient Undergrad."
                        });
                });

            modelBuilder.Entity("Catalog.DataAccess.Entities.BookTopic", b =>
                {
                    b.Property<int>("BookTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookTopicId"));

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookTopicId");

                    b.ToTable("BookTopic");

                    b.HasData(
                        new
                        {
                            BookTopicId = 1,
                            Topic = "distributed systems"
                        },
                        new
                        {
                            BookTopicId = 2,
                            Topic = "undergraduate school"
                        });
                });

            modelBuilder.Entity("Catalog.DataAccess.Entities.Book", b =>
                {
                    b.HasOne("Catalog.DataAccess.Entities.BookTopic", "BookTopic")
                        .WithMany("Books")
                        .HasForeignKey("BookTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookTopic");
                });

            modelBuilder.Entity("Catalog.DataAccess.Entities.BookTopic", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
